### ISSUE TITLE
Fail with no Redis

### ISSUE THREAD

**Issue by mikeruss1** [CIDRAM/CIDRAM#388]
as an experiment I tried a GET with Redis closed. No surprise I got ...
 Fatal error: Uncaught RedisException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\wamp\xxx\vault\Maikuolan\Common\Cache.php on line 272

no doubt the same will happen with PDO and Memcached.

would be nice if CIDRAM fell back to flat files until service resumed ? 
not worth a lot of effort of course

**Comment by Maikuolan** [comment]
Good idea. I'll see what I can do about this tomorrow.

**Comment by mikeruss1** [comment]
more annoying, the front end wont load either. Had to manually change config.yml. This bit is worth changing.

**Comment by mikeruss1** [comment]
should you fix this there is the chance of considerable user confusion. Tracking etc will move from Redis to Flat files then back again. While the log will look like nothing has happened. Maybe add a reference in the log to the tracking source? Presumably you will want the service to auto revert to Redis once it can, so you cant change the config.

**Comment by eurobank** [comment]
Sorry for highjacking, but also PLEASE make sure that only one caching is enabled (acu,memcached,redis,pdo). 

Today by mistake (while checking something) i had Redis AND PDO enabled, leading to a GREAT CRASH.

**Comment by Maikuolan** [comment]
*Partially* implemented. Those exceptions shouldn't appear anymore.

Still need to work on a better fallback mechanism and ways to prevent it when not wanted.

**Comment by mikeruss1** [comment]
tested and works. Frontend and core opens using flat files. Response is slow but I guess its wating for redis to reply. Suggest with frontend there should be feedback to confirm whats happened, maybe a popup?

I got a checksum error with the sig updates.

**Comment by Maikuolan** [comment]
> I got a checksum error with the sig updates.

Yeah.. Accidentally committed my copy of the signature files via Git bash when committing everything else earlier today a little prematurely (pushing too many commits at once, did the wrong `git add ...`), so some signature updates got merged in with an unrelated commit. My bad. '^.^

I had been planning to hold out another day or two, so as to avoid pushing out signature updates too quickly and thus avoid annoying users too much with too many updates, but seeing as I've already committed them early by mistake, after checking whether there are any last minute changes worth including tonight, I'll go ahead and push a new signatures update commit with checksums updated accordingly.

**Comment by eurobank** [comment]
@Maikuolan 

Maybe you missed it (maybe not), it would be easy for that check?

_

> Sorry for highjacking, but also PLEASE make sure that only one caching is enabled (acu,memcached,redis,pdo).
> 
> Today by mistake (while checking something) i had Redis AND PDO enabled, leading to a GREAT CRASH.

_

**Comment by Maikuolan** [comment]
> Response is slow but I guess its wating for redis to reply. Suggest with frontend there should be feedback to confirm whats happened, maybe a popup?

If it were a popup, I can foresee it potentially annoying some users if it comes up all the time. Maybe I just need to include some more debug information or maybe describe the results of the process as it stands at the time of viewing at the cache page?

> Maybe you missed it (maybe not), it would be easy for that check?

It should be easy to do, but in order to have it be able to fall back onto flatfiles, as well as avoid it switching over to different mechanisms when we don't want it to do that, I'm thinking we'll probably want it to be toggleable via a new configuration directive, something where we can explicitly tell it whether it's allowed to switch, and to what.

**Comment by eurobank** [comment]
@Maikuolan Why switch to something? 

While saving the cfg and TWO caching options are found enabled, display a popup and don't allow to save until one (or none = flatfiles) is selected.

**Comment by mikeruss1** [comment]
> If it were a popup, I can foresee it potentially annoying some users if it comes up all the time. Maybe I just need to include some more debug information or maybe describe the results of the process as it stands at the time of viewing at the cache page?
> 
I reckon the key thing is the user needs to know what has happened straight after the login.

**Comment by Maikuolan** [comment]
> I'll go ahead and push a new signatures update commit with checksums updated accordingly.

Done.
